version: '3'

networks:
  asupd:
volumes:
  mariadbvol:


services:
  app:
    container_name: tag-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1090:1090"
    # restart: unless-stopped
    depends_on:
      - migrate
    networks:
      - asupd
  migrate:
    image: migrate/migrate
    volumes:
        - ./migrations:/migrations
    command: ["-database", "mysql://tag_service:password@tcp(tag-mariadb:3306)/tag_service", "-path", "/migrations", "up"]
    depends_on:                     
      mariadb:
        condition: service_healthy
    networks:
      - asupd
    tty: true
  mariadb:
    container_name: tag-mariadb
    image: "mariadb:11.2"
    restart: unless-stopped
    networks:
      - asupd
    environment:
      MARIADB_DATABASE: tag_service
      MARIADB_USER: tag_service
      MARIADB_PASSWORD: password
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mariadbvol:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
