CREATE TABLE IF NOT EXISTS logs(
    id     INT unsigned  AUTO_INCREMENT PRIMARY KEY,
    alias VARCHAR(255) NOT NULL,
    login     VARCHAR(255)  NOT NULL,
    date_registered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);